name: CI-Test
on: push
env:
  PROJECT_ROOT: .
  UNITY_VERSION: 2019.4.1
jobs:
  testAllModes:
    name: Run Unity Testing
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: actions/cache@v1
        with:
          path: C:\\Users\\runneradmin\\AppData\\Local\\Temp\\chocolatey
          key: choco-unity-${{ env.UNITY_VERSION }}

      - uses: actions/cache@v1
        with:
          path: .\\Library
          key: unity-library-${{ env.UNITY_VERSION }}

      - run: choco install -y unity --version=${{ env.UNITY_VERSION }}
        shell: cmd

      - shell: cmd
        env:
          UNITY_MAIL: ${{ secrets.UNITY_MAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        run: '"C:\\Program Files\\Unity\\Editor\\Unity.exe" ^
                -batchmode -quit ^
                -username "%UNITY_MAIL%" ^
                -password "%UNITY_PASSWORD%" ^
                -serial "%UNITY_SERIAL%" ^
                -projectPath "%PROJECT_ROOT%" ^
                -executeMethod CI.Builder.Build ^
                -logfile -'

      - uses: actions/upload-artifact@v1
        with:
          name: Build.unitypackage
          path: Build.unitypackage
